#ifndef __DEFS_H
#define __DEFS_H

#define SERVEUR_ID				0

#define IDLE_FLAG				0
#define BUSY_FLAG				1


#define MAX_DATA_LENGTH			4095
#define PACKET_OVERHEAD			4

#define MAX_OFFSET				2047
#define MAX_LENGTH				32
#define MAX_WINDOWS				2079

#define CLIENT_NOT_CONNECTED	0
#define CLIENT_CONNECTED		1
#define CLIENT_REGISTERED		2
#define	CLIENT_BUSY				3

// Commands

#define DEST_SERVER					0x00
#define DEST_CLIENT					0x80
#define REQ_MSG						0x00
#define IND_MSG						0x40
#define CTRL_MSG					0x00
#define DATA_MSG					0x20

#define REQ_CLIENT_REG				(0x00 | (DEST_SERVER | REQ_MSG | CTRL_MSG))
#define REQ_CLIENT_LIST				(0x01 | (DEST_SERVER | REQ_MSG | CTRL_MSG))
#define REQ_CLIENT_UPDATE_STATUS	(0x02 | (DEST_SERVER | REQ_MSG | CTRL_MSG))

#define IND_SERVER_ERROR			(0x00 | (DEST_SERVER | IND_MSG | CTRL_MSG))
#define IND_CLIENT_PING				(0x01 | (DEST_SERVER | IND_MSG | CTRL_MSG))
#define IND_CLIENT_CLOSE			(0x03 | (DEST_SERVER | IND_MSG | CTRL_MSG))

#define REQ_CLIENT_PING				(0x00 | (DEST_CLIENT | REQ_MSG | CTRL_MSG))
#define REQ_SERVER_UPDATE_STATUS	(0x01 | (DEST_CLIENT | REQ_MSG | CTRL_MSG))
#define REQ_CONNECTION				(0x02 | (DEST_CLIENT | REQ_MSG | CTRL_MSG))
#define REQ_FILE_TRANSFER			(0x03 | (DEST_CLIENT | REQ_MSG | CTRL_MSG))
#define REQ_CONNECTION_CLOSE		(0x05 | (DEST_CLIENT | REQ_MSG | CTRL_MSG))

#define CHAT_DATA					(0x00 | (DEST_CLIENT | REQ_MSG | DATA_MSG))
#define FILE_DATA					(0x01 | (DEST_CLIENT | REQ_MSG | DATA_MSG))

#define IND_CLIENT_ERROR			(0x00 | (DEST_CLIENT | IND_MSG | CTRL_MSG))
#define IND_REG_ACCEPT				(0x01 | (DEST_CLIENT | IND_MSG | CTRL_MSG))
#define IND_CLIENT_LIST				(0x02 | (DEST_CLIENT | IND_MSG | CTRL_MSG))
#define IND_CONNECTION_ACCEPT		(0x03 | (DEST_CLIENT | IND_MSG | CTRL_MSG))
#define IND_FILE_TRANSFER_ACCEPT	(0x04 | (DEST_CLIENT | IND_MSG | CTRL_MSG))
#define IND_FILE_TRANSFER_CLOSE		(0x06 | (DEST_CLIENT | IND_MSG | CTRL_MSG))
#define IND_SERVER_CLOSE			(0x07 | (DEST_CLIENT | IND_MSG | CTRL_MSG))

#define ACK_FILE_DATA				(0x01 | (DEST_CLIENT | IND_MSG | DATA_MSG))



// Error codes
#define UNKNOWN_COMMAND				1
#define UNEXPECTED_COMMAND			2
#define ERROR_IN_MSG_FORMAT			3	

#define ALIAS_ALREADY_EXIST			4
#define ALIAS_TOO_LONG				5
#define ALIAS_TOO_SHORT				6
#define CLIENT_LIST_FULL			7

#define INVALID_PARAMETERS			8
#define CONN_REQ_REJECT				9
#define CONN_REQ_REJECT_BUSY		10
#define FILE_TRANSFER_REJECT		11
#define FILE_TRANSFER_REJECT_BUSY	12
#define FILE_TRANSFER_CRC_ERROR		13
#define FILE_TRANSFER_STOP			14
#define FILE_TRANSFER_ERROR			15


#define ROUTING_ERROR				16

#endif